import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { FormContext, FormProvider } from './contextAPi/FormContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Campaign Creation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <FormProvider>
        {children}
        </FormProvider>
      </body>
    </html>
  );
}
